name = input("What is your name?" )
dream_job = input("what is your dream job?" )
dream_age = input("At what age do you want to achieve your dream?" )


print()
print("Dear", name + ",")
print()
print("I am writing this letter from the future.")
print("You kept your promise and never gave up.")
print("You studied even on difficult days.")
print("You stopped copying code and started understanding it.")
print("You are an amazing",dream_job + ".")
print("You achieved your dream at the age of", dream_age + ".")
print("You found a place where you can keep learning and build meaningful AI that helps people.")
print()
print("I still remember the day you started leaening Python.")
print("You were scared, but you kept going.")
print("You made mistakes, fixed them and became stronger.")
print()
print("I am very proud of you,", name + ".")
print("Thank you for not giving up.")
print()
print("Love,")
print("Future", name)
